services:
  app:
    container_name: "zoomapp"
    build: . 
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - "zoomnetwork"

  db:
    container_name: "zoomdb"
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - "zoomnetwork"

volumes:
  postgres_data:

networks:
  zoomnetwork:
    driver: bridge
